### ISSUE TITLE
2014-2015

### ISSUE THREAD

**Issue by marcopegano** [NyxAether/DVF#1]
Hello, would it be possible to provide cleaned files for 2014-2015 in csv to allow people with R to download the file? Thank you.

**Comment by NyxAether** [comment]
Hi @marcopegano ,

Since I'm already borderline with the github terms of services, I don't plan to have multiple file types. Furthermore, csv files don't keep *metadata* information like the data type used in each column.
Though, I'm aware of the inconvenience of pickle and aim to change everything to parquet (which, I think, is more convenient for R users).
